/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DemoMap: typeof import('./../play/app/components/DemoMap.vue')['default']
    MapboxAttributionControl: typeof import('#mapbox/components/controls/AttributionControl.vue')['default']
    MapboxDrawControl: typeof import('#mapbox/components/extensions/DrawControl.vue')['default']
    MapboxFullscreenControl: typeof import('#mapbox/components/controls/FullscreenControl.vue')['default']
    MapboxGeolocateControl: typeof import('#mapbox/components/controls/GeolocateControl.vue')['default']
    MapboxLayer: typeof import('#mapbox/components/Layer.vue')['default']
    MapboxMap: typeof import('#mapbox/components/Map.vue')['default']
    MapboxMarker: typeof import('#mapbox/components/Marker.vue')['default']
    MapboxNavigationControl: typeof import('#mapbox/components/controls/NavigationControl.vue')['default']
    MapboxPopup: typeof import('#mapbox/components/Popup.vue')['default']
    MapboxScaleControl: typeof import('#mapbox/components/controls/ScaleControl.vue')['default']
    MapboxSource: typeof import('#mapbox/components/Source.vue')['default']
    MapboxTiandituLayer: typeof import('#mapbox/components/extensions/TiandituLayer.vue')['default']
    MapboxWmsLayer: typeof import('#mapbox/components/extensions/WmsLayer.vue')['default']
    MapboxWmtsLayer: typeof import('#mapbox/components/extensions/WmtsLayer.vue')['default']
    MapShowcase: typeof import('./../play/app/components/MapShowcase.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_c5faf6b69d02c9bcb1bd890705c42ebf/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_c5faf6b69d02c9bcb1bd890705c42ebf/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UColorModeButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_c5faf6b69d02c9bcb1bd890705c42ebf/node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue')['default']
    UDashboardGroup: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_c5faf6b69d02c9bcb1bd890705c42ebf/node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
    UDashboardPanel: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_c5faf6b69d02c9bcb1bd890705c42ebf/node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue')['default']
    UDashboardSidebar: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_c5faf6b69d02c9bcb1bd890705c42ebf/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
    UIcon: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_c5faf6b69d02c9bcb1bd890705c42ebf/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_c5faf6b69d02c9bcb1bd890705c42ebf/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UNavigationMenu: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_c5faf6b69d02c9bcb1bd890705c42ebf/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPage: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_c5faf6b69d02c9bcb1bd890705c42ebf/node_modules/@nuxt/ui/dist/runtime/components/Page.vue')['default']
    UPageCard: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_c5faf6b69d02c9bcb1bd890705c42ebf/node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue')['default']
    UPageGrid: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_c5faf6b69d02c9bcb1bd890705c42ebf/node_modules/@nuxt/ui/dist/runtime/components/PageGrid.vue')['default']
    UPageHero: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_c5faf6b69d02c9bcb1bd890705c42ebf/node_modules/@nuxt/ui/dist/runtime/components/PageHero.vue')['default']
    URadioGroup: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_c5faf6b69d02c9bcb1bd890705c42ebf/node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue')['default']
    USelect: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_c5faf6b69d02c9bcb1bd890705c42ebf/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USeparator: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_c5faf6b69d02c9bcb1bd890705c42ebf/node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    USlider: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_c5faf6b69d02c9bcb1bd890705c42ebf/node_modules/@nuxt/ui/dist/runtime/components/Slider.vue')['default']
    USwitch: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_c5faf6b69d02c9bcb1bd890705c42ebf/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
  }
}
